### ISSUE TITLE
add getting started wiki page

### ISSUE THREAD

**Issue by ErikEJ** [crhairr/EntityFrameworkCore.MongoDb#1]
https://github.com/ErikEJ/EntityFramework.SqlServerCompact/wiki/Using-EF-Core-with-SQL-Server-Compact-in-Traditional-.NET-Applications

**Comment by crhairr** [comment]
It's already in the works! I've started a documentation branch for adding all of the relevant XML docs to the code as well for consumption with Intellisense.

**Comment by crhairr** [comment]
The first two wiki entries have been created:
https://github.com/crhairr/EntityFrameworkCore.MongoDb/wiki/Getting-Started

**Comment by ErikEJ** [comment]
Great - the use of attributes looks slightly strange in a EF Core context, in particular this:
[MongoDatabase("zooDb")] - could the UseMongoDb method be extended with a second parameters for the database name?

**Comment by crhairr** [comment]
Not currently, but you can configure the database in OnModelCreating (essentially what the attribute is doing):

```C#
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            new InternalModelBuilder(modelBuilder.Model.AsModel())
                .MongoDb(ConfigurationSource.Explicit)
                .FromDatabase("zooDb");
        }
```

This is quite clunky since Microsoft decided to split their builders into public and internal versions where the `InternalModelBuilder` takes a Model instead of an `IMutableModel` for some unobvious reason. This is why I prefer the attribute. I will probably end up adding a property to the options extension since that would be more concise than the above. But I think that anybody already familiar with the MongoDb C# driver would also prefer the straight-forward, declarative, aspect-oriented style of the attributes.

FWIF, the Bson* attributes are what the driver uses to create its `BsonClassMap` mappings, so I've implemented conventions to support those to make it easier for people already familiar with the driver to adopt this provider. I do intend at some point to add conventions to the adapter to support attributes used by EF Core (like `Key` and `DatabaseGenerated`) so that a `BsonClassMap` can be created from a "standard" EF Core model.

**Comment by vdavi** [comment]
This is fantastic! Can you tell me if there is built in support for accessing the .aggregate functionality for mongoDb?
I'v been spending months evaluating a completely different tech stack, (Meteor) and I've hit a dead end regarding aggregate usage while also using angular 2. (Long story)

**Comment by crhairr** [comment]
**EDIT**: this project wraps the MongoDB C# Driver, and `DbSet<T>` is essentially implemented as `mongoDatabase.GetCollection<T>.AsQueryable<T>()`. Anything that you can do with their [Linq provider](https://github.com/mongodb/mongo-csharp-driver/blob/master/tests/MongoDB.Driver.Tests/Linq/MongoQueryableTests.cs), you can do with a linq query using EFCore-MongoDB.

But, if you need more than that and must use the aggregation framework directly, read on...

**END EDIT**

It's possible, but there's currently no *direct* support for it through EFCore-MongoDB. I plan to expose this a bit more fluidly using extension methods on `DbSet<T>`. In the meantime, you should be able to use the MongoDB C# driver's [aggregation framework](https://docs.mongodb.com/getting-started/csharp/aggregation/) by injecting an [`IMongoDbConnection`](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/develop/src/Blueshift.EntityFrameworkCore.MongoDB/Storage/IMongoDbConnection.cs) into your class constructor and using it something like this:

```csharp
public IEnumerable<T> AggregateTheThings<T>()
{
    var pipeline = new AggregateArgs()
    {
        /*do your thing here*/
    };
    return _mongoDbConnection
        .GetCollection<T>
        .Aggregate(pipeline);
}
```

You can find some examples of using the driver's Aggregate method here: http://mikaelkoskinen.net/post/mongodb-aggregation-framework-examples-in-c.

**Note**: you might encounter some issues if your collection contains polymorphic documents. Be sure to supply the base document type to `GetCollection<T>`. I already have a fix for this that will ensure that the correct collection for a polymorphic subtype is always returned, which will be committed in the next few days as part of an [Identity provider](https://github.com/aspnet/Identity) for MongoDB.
